<a href="https://colab.research.google.com/github/Coder-vats/Calculator/blob/master/Fake_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('/content/drive/MyDrive/train.csv')

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
data=df[df['id']==0]
data['text']

0    House Dem Aide: We Didn’t Even See Comey’s Let...
Name: text, dtype: object

In [9]:
df=df.dropna()

In [10]:
X=df.drop('label',axis=1)

In [11]:
y=df['label']

In [12]:
X.shape

(18285, 4)

In [13]:
import tensorflow as tf

In [14]:
tf.__version__

'2.7.0'

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [16]:
voc_size=5000

In [17]:
messages=X.copy()

In [18]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:
messages.reset_index(inplace=True)

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [23]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4798, 3038, 3690, 971, 1601, 1567, 2366, 1349, 2799, 2928],
 [2954, 1684, 650, 1166, 3863, 4322, 3503],
 [4148, 123, 3583, 2950],
 [4134, 1748, 1618, 4918, 4198, 544],
 [4340, 3863, 3718, 4705, 3393, 2718, 3863, 4955, 4306, 1646],
 [3402,
  824,
  1460,
  2754,
  1562,
  4863,
  3958,
  4234,
  4542,
  2458,
  4015,
  3418,
  2179,
  4692,
  3503],
 [1734, 1207, 1478, 1761, 1458, 1652, 3162, 3534, 4140, 874, 1698],
 [2407, 1734, 2629, 1791, 3820, 3344, 4863, 4760, 4140, 874, 1698],
 [4082, 1508, 3873, 4821, 2742, 4001, 4068, 118, 4863, 26],
 [922, 650, 1573, 4572, 3409, 132, 4268, 1493],
 [3403, 1875, 3718, 4704, 1254, 1777, 1337, 3858, 2692, 1100, 4764],
 [4918, 1418, 1601, 4001, 4863, 3820],
 [1748, 3581, 3484, 2308, 432, 2250, 3173, 4363, 4536],
 [2050, 1083, 926, 2811, 2335, 485, 4490, 4140, 874, 1698],
 [4588, 1069, 2091, 120, 64, 4140, 874, 1698],
 [4167, 4289, 181, 3681, 1916, 609, 2346, 3010, 1425, 1021],
 [1073, 4061, 1684],
 [578, 2979, 2964, 3431, 4863, 2814, 4560, 3503],


In [24]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1349 2799 2928]
 [   0    0    0 ... 3863 4322 3503]
 [   0    0    0 ...  123 3583 2950]
 ...
 [   0    0    0 ... 4140  874 1698]
 [   0    0    0 ... 3500 1212 3538]
 [   0    0    0 ... 3032 4408 3851]]


In [25]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [29]:
!pip install tensorflow==2.7

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [30]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 11s 15ms/step - loss: 0.3059 - accuracy: 0.8548 - val_loss: 0.2023 - val_accuracy: 0.9145
Epoch 2/10
192/192 [==============================] - 3s 16ms/step - loss: 0.1340 - accuracy: 0.9487 - val_loss: 0.1976 - val_accuracy: 0.9186
Epoch 3/10
192/192 [==============================] - 4s 21ms/step - loss: 0.0914 - accuracy: 0.9672 - val_loss: 0.2107 - val_accuracy: 0.9150
Epoch 4/10
192/192 [==============================] - 4s 22ms/step - loss: 0.0671 - accuracy: 0.9780 - val_loss: 0.2904 - val_accuracy: 0.9132
Epoch 5/10
192/192 [==============================] - 3s 16ms/step - loss: 0.0426 - accuracy: 0.9860 - val_loss: 0.3191 - val_accuracy: 0.9099
Epoch 6/10
192/192 [==============================] - 3s 14ms/step - loss: 0.0269 - accuracy: 0.9915 - val_loss: 0.3892 - val_accuracy: 0.9110
Epoch 7/10
192/192 [==============================] - 3s 15ms/step - loss: 0.0195 - accuracy: 0.9944 - val_loss: 0.4614 - val_accuracy: 0.911

In [31]:
y_pred=(model1.predict(X_test) > 0.5).astype("int32")

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(y_test,y_pred)

array([[3137,  282],
       [ 264, 2352]])

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9095277547638774

In [35]:
import pandas as pd
from sklearn.metrics import classification_report

report_dict = classification_report(y_test, y_pred, output_dict=True)
pd.DataFrame(report_dict)

0            1  accuracy    macro avg  weighted avg
precision     0.922376     0.892938  0.909528     0.907657      0.909616
recall        0.917520     0.899083  0.909528     0.908301      0.909528
f1-score      0.919941     0.896000  0.909528     0.907971      0.909563
support    3419.000000  2616.000000  0.909528  6035.000000   6035.000000